name: Test PR - PomodoroTimer

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Instalar dependências
      run: |
        if exist package.json npm install

    - name: Rodar ESLint
      run: |
        if exist package.json npm run lint
